### ISSUE TITLE
Art of Electronics Solutions Licensing

### ISSUE THREAD

**Issue by milesdai** [OpenTextbookSolutions/open-textbook-solutions#18]
Hi there! I'm the maintainer of milesdai/TAoE3Solutions, and I'm glad to see that you're finding the project helpful for your work! One thing I wanted to bring to your attention is that my project is under an MIT License which puts no restrictions on the use of the work but does require that the license text be included with all copies/substantial portions of the software.

One suggestion that would solve this (among other problems you may face) might be to use a Git submodule to include the repo. This would allow you to include licensing information, easily pull changes from my repo into your project, and also provide maintainers of your site with a pointer back to the TAoE3Solutions source repo. Just a suggestion though (you could just as easily copy the text of the license into the TeX file to resolve the problem)!

**Comment by K4LCIFER** [comment]
> but does require that the license text be included with all copies/substantial portions of the software.

You are absolutely correct! I apologize for this mistake. I misunderstood what the proper method was for including MIT code in a GPL licensed project. I knew you could combine them no problem, but I mistakenly missed the part in the MIT license that states that the MIT license still has to be included in all copies of the software. I will fix this right away. Temporarily, I think that putting the MIT license in the same subdirectory that your project's code is located in should suffice. 

> One suggestion that would solve this (among other problems you may face) might be to use a Git submodule to include the repo. 

I will definitely look into that. I want to avoid manual copies of things as much as I possibly can. Thank you for your suggestion!

**Comment by K4LCIFER** [comment]
Ok I will close this for now as I have added your repo as a submodule. I do have some concerns over this format, but I need to wait and see how some things turn out. This is definitely a plausible solution that solves a few issues that I had.
